name: mem-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11                 # ACTUALIZADO: Resuelve el error de 'Self' typing
  - pip
  - numpy
  - pandas
  - librosa
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - scikit-learn
  - ffmpeg                      # Crucial para yt-dlp y librosa
  - jupyterlab
  - ipykernel
  - nltk
  - sentencepiece
  - ftfy
  - pyarrow
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1         # Asegura compatibilidad con PyTorch y GPU

  - pip:
      - python-dotenv
      - transformers            # Para cuando lleguemos al modelado de texto
      - accelerate              # Para manejo eficiente de modelos grandes
      - lyricsgenius            # Versión moderna compatible con Py3.11
      - spotipy                 # Para ExtractDataV2 (Paso 1)
      - langdetect              # Para ExtractDataV2 (Paso 2)
      - yt-dlp                  # Para ExtractDataV2 (Paso 3)